Traceback (most recent call last):
  File "/Users/humphreyyang/anaconda3/envs/quantecon/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/humphreyyang/anaconda3/envs/quantecon/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/humphreyyang/anaconda3/envs/quantecon/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/humphreyyang/anaconda3/envs/quantecon/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/humphreyyang/anaconda3/envs/quantecon/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/humphreyyang/anaconda3/envs/quantecon/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/humphreyyang/anaconda3/envs/quantecon/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/humphreyyang/anaconda3/envs/quantecon/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
continents = grouped.groups.keys()

for continent in continents:
    sns.kdeplot(grouped.get_group(continent).loc['2015'].unstack(), label=continent, fill=True)

plt.title('Real minimum wages in 2015')
plt.xlabel('US dollars')
plt.legend()
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
File [0;32m~/anaconda3/envs/quantecon/lib/python3.9/site-packages/pandas/core/indexes/datetimes.py:611[0m, in [0;36mDatetimeIndex.get_loc[0;34m(self, key)[0m
[1;32m    610[0m [38;5;28;01mtry[39;00m:
[0;32m--> 611[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_partial_date_slice[49m[43m([49m[43mreso[49m[43m,[49m[43m [49m[43mparsed[49m[43m)[49m
[1;32m    612[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m [38;5;28;01mas[39;00m err:

File [0;32m~/anaconda3/envs/quantecon/lib/python3.9/site-packages/pandas/core/indexes/datetimelike.py:310[0m, in [0;36mDatetimeIndexOpsMixin._partial_date_slice[0;34m(self, reso, parsed)[0m
[1;32m    306[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m([38;5;28mself[39m) [38;5;129;01mand[39;00m (
[1;32m    307[0m     (t1 [38;5;241m<[39m [38;5;28mself[39m[[38;5;241m0[39m] [38;5;129;01mand[39;00m t2 [38;5;241m<[39m [38;5;28mself[39m[[38;5;241m0[39m]) [38;5;129;01mor[39;00m (t1 [38;5;241m>[39m [38;5;28mself[39m[[38;5;241m-[39m[38;5;241m1[39m] [38;5;129;01mand[39;00m t2 [38;5;241m>[39m [38;5;28mself[39m[[38;5;241m-[39m[38;5;241m1[39m])
[1;32m    308[0m ):
[1;32m    309[0m     [38;5;66;03m# we are out of range[39;00m
[0;32m--> 310[0m     [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m
[1;32m    312[0m [38;5;66;03m# TODO: does this depend on being monotonic _increasing_?[39;00m
[1;32m    313[0m 
[1;32m    314[0m [38;5;66;03m# a monotonic (sorted) series can be sliced[39;00m

[0;31mKeyError[0m: 

The above exception was the direct cause of the following exception:

[0;31mKeyError[0m                                  Traceback (most recent call last)
Cell [0;32mIn[37], line 4[0m
[1;32m      1[0m continents [38;5;241m=[39m grouped[38;5;241m.[39mgroups[38;5;241m.[39mkeys()
[1;32m      3[0m [38;5;28;01mfor[39;00m continent [38;5;129;01min[39;00m continents:
[0;32m----> 4[0m     sns[38;5;241m.[39mkdeplot([43mgrouped[49m[38;5;241;43m.[39;49m[43mget_group[49m[43m([49m[43mcontinent[49m[43m)[49m[38;5;241;43m.[39;49m[43mloc[49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43m2015[39;49m[38;5;124;43m'[39;49m[43m][49m[38;5;241m.[39munstack(), label[38;5;241m=[39mcontinent, fill[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[1;32m      6[0m plt[38;5;241m.[39mtitle([38;5;124m'[39m[38;5;124mReal minimum wages in 2015[39m[38;5;124m'[39m)
[1;32m      7[0m plt[38;5;241m.[39mxlabel([38;5;124m'[39m[38;5;124mUS dollars[39m[38;5;124m'[39m)

File [0;32m~/anaconda3/envs/quantecon/lib/python3.9/site-packages/pandas/core/indexing.py:1153[0m, in [0;36m_LocationIndexer.__getitem__[0;34m(self, key)[0m
[1;32m   1150[0m axis [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39maxis [38;5;129;01mor[39;00m [38;5;241m0[39m
[1;32m   1152[0m maybe_callable [38;5;241m=[39m com[38;5;241m.[39mapply_if_callable(key, [38;5;28mself[39m[38;5;241m.[39mobj)
[0;32m-> 1153[0m [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_getitem_axis[49m[43m([49m[43mmaybe_callable[49m[43m,[49m[43m [49m[43maxis[49m[38;5;241;43m=[39;49m[43maxis[49m[43m)[49m

File [0;32m~/anaconda3/envs/quantecon/lib/python3.9/site-packages/pandas/core/indexing.py:1393[0m, in [0;36m_LocIndexer._getitem_axis[0;34m(self, key, axis)[0m
[1;32m   1391[0m [38;5;66;03m# fall thru to straight lookup[39;00m
[1;32m   1392[0m [38;5;28mself[39m[38;5;241m.[39m_validate_key(key, axis)
[0;32m-> 1393[0m [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_get_label[49m[43m([49m[43mkey[49m[43m,[49m[43m [49m[43maxis[49m[38;5;241;43m=[39;49m[43maxis[49m[43m)[49m

File [0;32m~/anaconda3/envs/quantecon/lib/python3.9/site-packages/pandas/core/indexing.py:1343[0m, in [0;36m_LocIndexer._get_label[0;34m(self, label, axis)[0m
[1;32m   1341[0m [38;5;28;01mdef[39;00m [38;5;21m_get_label[39m([38;5;28mself[39m, label, axis: AxisInt):
[1;32m   1342[0m     [38;5;66;03m# GH#5567 this will fail if the label is not present in the axis.[39;00m
[0;32m-> 1343[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mobj[49m[38;5;241;43m.[39;49m[43mxs[49m[43m([49m[43mlabel[49m[43m,[49m[43m [49m[43maxis[49m[38;5;241;43m=[39;49m[43maxis[49m[43m)[49m

File [0;32m~/anaconda3/envs/quantecon/lib/python3.9/site-packages/pandas/core/generic.py:4236[0m, in [0;36mNDFrame.xs[0;34m(self, key, axis, level, drop_level)[0m
[1;32m   4234[0m             new_index [38;5;241m=[39m index[loc]
[1;32m   4235[0m [38;5;28;01melse[39;00m:
[0;32m-> 4236[0m     loc [38;5;241m=[39m [43mindex[49m[38;5;241;43m.[39;49m[43mget_loc[49m[43m([49m[43mkey[49m[43m)[49m
[1;32m   4238[0m     [38;5;28;01mif[39;00m [38;5;28misinstance[39m(loc, np[38;5;241m.[39mndarray):
[1;32m   4239[0m         [38;5;28;01mif[39;00m loc[38;5;241m.[39mdtype [38;5;241m==[39m np[38;5;241m.[39mbool_:

File [0;32m~/anaconda3/envs/quantecon/lib/python3.9/site-packages/pandas/core/indexes/datetimes.py:613[0m, in [0;36mDatetimeIndex.get_loc[0;34m(self, key)[0m
[1;32m    611[0m             [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_partial_date_slice(reso, parsed)
[1;32m    612[0m         [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m [38;5;28;01mas[39;00m err:
[0;32m--> 613[0m             [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m(key) [38;5;28;01mfrom[39;00m [38;5;21;01merr[39;00m
[1;32m    615[0m     key [38;5;241m=[39m parsed
[1;32m    617[0m [38;5;28;01melif[39;00m [38;5;28misinstance[39m(key, dt[38;5;241m.[39mtimedelta):
[1;32m    618[0m     [38;5;66;03m# GH#20464[39;00m

[0;31mKeyError[0m: '2015'
KeyError: '2015'

